// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/atoms/AppLink.vue')['default']
    Badge: typeof import('./components/atoms/Badge.vue')['default']
    Btn: typeof import('./components/atoms/Btn.vue')['default']
    copy: typeof import('./components/atoms/InputText copy.vue')['default']
    InputText: typeof import('./components/atoms/InputText.vue')['default']
    ListPosts: typeof import('./components/organisms/ListPosts.vue')['default']
    Post: typeof import('./components/organisms/Post.vue')['default']
    PostHeader: typeof import('./components/PostHeader.vue')['default']
    PublicContactSection: typeof import('./components/organisms/PublicContactSection.vue')['default']
    PublicExperiencesSection: typeof import('./components/organisms/PublicExperiencesSection.vue')['default']
    PublicHeroSection: typeof import('./components/organisms/PublicHeroSection.vue')['default']
    PublicSkillsetSection: typeof import('./components/organisms/PublicSkillsetSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./components/atoms/Tab.vue')['default']
    Tabs: typeof import('./components/atoms/Tabs.vue')['default']
    Textarea: typeof import('./components/atoms/Textarea.vue')['default']
    TextArea: typeof import('./components/atoms/TextArea.vue')['default']
    TextCopy: typeof import('./components/atoms/TextCopy.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/organisms/TheFooter.vue')['default']
    TheHeader: typeof import('./components/organisms/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ToggleDark: typeof import('./components/atoms/ToggleDark.vue')['default']
  }
}
