/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/blog/[slug]': RouteRecordInfo<'/blog/[slug]', '/blog/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/contato': RouteRecordInfo<'/contato', '/contato', Record<never, never>, Record<never, never>>,
    '/projetos/': RouteRecordInfo<'/projetos/', '/projetos', Record<never, never>, Record<never, never>>,
    '/projetos/[slug]': RouteRecordInfo<'/projetos/[slug]', '/projetos/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/sobre': RouteRecordInfo<'/sobre', '/sobre', Record<never, never>, Record<never, never>>,
  }
}
